class Aluno:
    def __init__(self, nome_completo, data_nascimento, email, nome_mae, cpf,
                 carteira_identidade, data_emissao_identidade, orgao_emissor_identidade,
                 numero_titulo_eleitoral, numero_serie_documento_militar,
                 endereco_residencial, cidade_residencia, estado_residencia,
                 telefone_contato, link_lattes, reservas_vagas, siape_ufpel,
                 nome_curso_graduacao, tipo_curso_graduacao, instituicao_graduacao,
                 ano_conclusao_graduacao, nome_curso_mestrado, tipo_curso_mestrado,
                 instituicao_mestrado, ano_conclusao_mestrado, local_trabalho,
                 atuacao, lingua_inglesa_leitura, lingua_inglesa_escrita,
                 lingua_inglesa_fala, tipo_inscricao, semestre_ingresso,
                 orientador_preferencial, segunda_opcao, terceira_opcao,
                 dedicacao_integral, vinculo_empregaticio, interesse_bolsa,
                 projeto_doutorado_pdf, titulo_publicacao_1, local_publicacao_1,
                 tipo_publicacao_1, qualis_publicacao_1, comprovacao_publicacao_1,
                 titulo_publicacao_2, local_publicacao_2, tipo_publicacao_2,
                 qualis_publicacao_2, comprovacao_publicacao_2, titulo_publicacao_3,
                 local_publicacao_3, tipo_publicacao_3, qualis_publicacao_3,
                 comprovacao_publicacao_3, titulo_publicacao_4, local_publicacao_4,
                 tipo_publicacao_4, qualis_publicacao_4, comprovacao_publicacao_4,
                 titulo_publicacao_5, local_publicacao_5, tipo_publicacao_5,
                 qualis_publicacao_5, comprovacao_publicacao_5, curriculo_lattes,
                 diploma_graduacao, diploma_mestrado, historico_graduacao,
                 historico_mestrado, carteira_identidade_copia, cpf_copia,
                 titulo_eleitor, certificado_quitacao_militar, certidao_casamento,
                 comprovante_pagamento, documentacao_edital, outro_documento,
                 id_usuario, timestamp, last_updated, created_by, updated_by,
                 draft, ip, id, key):
        self.nome_completo = nome_completo
        self.data_nascimento = data_nascimento
        self.email = email
        self.nome_mae = nome_mae
        self.cpf = cpf
        self.carteira_identidade = carteira_identidade
        self.data_emissao_identidade = data_emissao_identidade
        self.orgao_emissor_identidade = orgao_emissor_identidade
        self.numero_titulo_eleitoral = numero_titulo_eleitoral
        self.numero_serie_documento_militar = numero_serie_documento_militar
        self.endereco_residencial = endereco_residencial
        self.cidade_residencia = cidade_residencia
        self.estado_residencia = estado_residencia
        self.telefone_contato = telefone_contato
        self.link_lattes = link_lattes
        self.reservas_vagas = reservas_vagas
        self.siape_ufpel = siape_ufpel
        self.nome_curso_graduacao = nome_curso_graduacao
        self.tipo_curso_graduacao = tipo_curso_graduacao
        self.instituicao_graduacao = instituicao_graduacao
        self.ano_conclusao_graduacao = ano_conclusao_graduacao
        self.nome_curso_mestrado = nome_curso_mestrado
        self.tipo_curso_mestrado = tipo_curso_mestrado
        self.instituicao_mestrado = instituicao_mestrado
        self.ano_conclusao_mestrado = ano_conclusao_mestrado
        self.local_trabalho = local_trabalho
        self.atuacao = atuacao
        self.lingua_inglesa_leitura = lingua_inglesa_leitura
        self.lingua_inglesa_escrita = lingua_inglesa_escrita
        self.lingua_inglesa_fala = lingua_inglesa_fala
        self.tipo_inscricao = tipo_inscricao
        self.semestre_ingresso = semestre_ingresso
        self.orientador_preferencial = orientador_preferencial
        self.segunda_opcao = segunda_opcao
        self.terceira_opcao = terceira_opcao
        self.dedicacao_integral = dedicacao_integral
        self.vinculo_empregaticio = vinculo_empregaticio
        self.interesse_bolsa = interesse_bolsa
        self.projeto_doutorado_pdf = projeto_doutorado_pdf
        self.titulo_publicacao_1 = titulo_publicacao_1
        self.local_publicacao_1 = local_publicacao_1
        self.tipo_publicacao_1 = tipo_publicacao_1
        self.qualis_publicacao_1 = qualis_publicacao_1
        self.comprovacao_publicacao_1 = comprovacao_publicacao_1
        self.titulo_publicacao_2 = titulo_publicacao_2
        self.local_publicacao_2 = local_publicacao_2
        self.tipo_publicacao_2 = tipo_publicacao_2
        self.qualis_publicacao_2 = qualis_publicacao_2
        self.comprovacao_publicacao_2 = comprovacao_publicacao_2
        self.titulo_publicacao_3 = titulo_publicacao_3
        self.local_publicacao_3 = local_publicacao_3
        self.tipo_publicacao_3 = tipo_publicacao_3
        self.qualis_publicacao_3 = qualis_publicacao_3
        self.comprovacao_publicacao_3 = comprovacao_publicacao_3
        self.titulo_publicacao_4 = titulo_publicacao_4
        self.local_publicacao_4 = local_publicacao_4
        self.tipo_publicacao_4 = tipo_publicacao_4
        self.qualis_publicacao_4 = qualis_publicacao_4
        self.comprovacao_publicacao_4 = comprovacao_publicacao_4
        self.titulo_publicacao_5 = titulo_publicacao_5
        self.local_publicacao_5 = local_publicacao_5
        self.tipo_publicacao_5 = tipo_publicacao_5
        self.qualis_publicacao_5 = qualis_publicacao_5
        self.comprovacao_publicacao_5 = comprovacao_publicacao_5
        self.curriculo_lattes = curriculo_lattes
        self.diploma_graduacao = diploma_graduacao
        self.diploma_mestrado = diploma_mestrado
        self.historico_graduacao = historico_graduacao
        self.historico_mestrado = historico_mestrado
        self.carteira_identidade_copia = carteira_identidade_copia
        self.cpf_copia = cpf_copia
        self.titulo_eleitor = titulo_eleitor
        self.certificado_quitacao_militar = certificado_quitacao_militar
        self.certidao_casamento = certidao_casamento
        self.comprovante_pagamento = comprovante_pagamento
        self.documentacao_edital = documentacao_edital
        self.outro_documento = outro_documento
        self.id_usuario = id_usuario
        self.timestamp = timestamp
        self.last_updated = last_updated
        self.created_by = created_by
        self.updated_by = updated_by
        self.draft = draft
        self.ip = ip
        self.id = id
        self.key = key
